apiVersion: v1
kind: Service
metadata:
  name: svc-maven
  namespace: mavenapp
spec:
  selector:
    app: maven
  type: NodePort # ClusterIP, NodePort, LoadBalancer, ExternalName
  #  sessionAffinity: ClientIP
  ports:
    - port: 8080
      targetPort: 8080
